Feat: adicionado docker-compose-template

diff --git a/.github/workflows/generate-release.yml b/.github/workflows/generate-release.yml
--- a/.github/workflows/generate-release.yml
+++ b/.github/workflows/generate-release.yml
@@ -27,17 +27,18 @@ jobs:
       - name: Update package version, generate and push README
         run: |
           npm version ${{ github.ref_name }} --no-git-tag-version
-          WORKFLOW_FILE="generate-release.yml"
           sed -e "s/{{user}}/${{ github.actor }}/g" \
             -e "s/{{repo}}/${{ github.event.repository.name }}/g" \
-            -e "s/{{workflow_file}}/$WORKFLOW_FILE/g" \
-            -e "s/{{version}}/${{ github.ref_name }}/g" \
             README.template.md > README.md
+          sed -e "s/{{user}}/${{ github.actor }}/g" \
+            -e "s/{{repo}}/${{ github.event.repository.name }}/g" \
+            docker-compose.yml.template > docker-compose.yml
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git add README.md
+          git add docker-compose.yml
           git add package.json
-          git commit -m "Feat: Atualizado README.md"
+          git commit -m "Feat: Atualizado README.md e docker-compose.yml"
           git push origin HEAD:main
 
       - name: Install dependencies
@@ -46,7 +47,8 @@ jobs:
           if [ -d "./src" ]; then
               npm install
           else
-              echo "Pasta ./src não encontrada. Pulando instalação de dependências."
+              echo "./src folder not found."
+              exit 1
           fi
 
       - name: Cache Node.js modules
